# Generated by Django 3.2.2 on 2023-02-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='username',
        ),
    ]
